"""add video table

Revision ID: 017602b47c23
Revises: 133de69e89a2
Create Date: 2025-04-16 20:37:58.714847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017602b47c23'
down_revision = '133de69e89a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
