"""add video table

Revision ID: 017602b47c23
Revises: 133de69e89a2
Create Date: 2025-04-16 20:37:58.714847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017602b47c23'
down_revision = '133de69e89a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        pass
    # ### end Alembic commands ###



def downgrade():
    op.drop_table('videos')

    # ### end Alembic commands ###
