"""Add user_id to notes

Revision ID: 5e69d2ee211f
Revises: 
Create Date: 2025-04-16 07:42:19.797738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e69d2ee211f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('des',
               existing_type=mysql.VARCHAR(length=258),
               nullable=True)
        batch_op.alter_column('tags',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('categories',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('ispublic',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('note',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('ispublic',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('categories',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('tags',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('des',
               existing_type=mysql.VARCHAR(length=258),
               nullable=False)

    # ### end Alembic commands ###
